name: Dev Image build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.2"

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.DEV_S3_BUCKET }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ secrets.DEV_AWS_REGION }}" \
            -backend-config="access_key=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform fmt
        run: terraform fmt 
        
      - name: Terraform validate
        run: terraform validate
        
      - name: Terraform plan
        run: terraform plan -var-file=dev.tfvars

      - name: Terraform apply
        run: |
          terraform apply \
            -auto-approve \
            -var-file=dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.DEV_AWS_REGION }}

